#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: setup native build
description: sets up Rust, Zig, and cargo-zigbuild for native builds
runs:
  using: composite
  steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
      with:
        # Cross-compilation targets: Linux amd64 and arm64 (glibc)
        targets: >-
          x86_64-unknown-linux-gnu,
          aarch64-unknown-linux-gnu

    - name: Set up Zig
      uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29

    - name: Install cargo-zigbuild
      run: cargo install --locked cargo-zigbuild
      shell: bash
