# contains pattern definitions used in workflows "changes" step
# pattern syntax: https://github.com/micromatch/picomatch
all:
  - '**'
docs:
  - 'site3/**'
  - '.asf.yaml'
  - '*.md'
  - '**/*.md'
  - '.github/changes-filter.yaml'
  - '.github/ISSUE_TEMPLATE/**'
need_owasp:
  - 'pom.xml'
  - '**/pom.xml'
  - 'src/owasp-dependency-check-false-positives.xml'
  - 'src/owasp-dependency-check-suppressions.xml'