#!/bin/bash
set -x

BK_RELEASE_VERSION=`curl --silent https://api.github.com/repos/apache/bookkeeper/releases/latest | jq '.tag_name' | sed "s/\"release-\([0-9.]*\).*/\1/"`

docker build --build-arg BK_VERSION=$BK_RELEASE_VERSION -t $IMAGE_NAME .
