#!/bin/bash
set -x
# When we build 'latest' tag we want to not override BK_VERSION variable
if [[ "$DOCKER_TAG" = "latest" ]]
then
  docker build -t $IMAGE_NAME .
else
  docker build --build-arg BK_VERSION=$DOCKER_TAG -t $IMAGE_NAME .
fi
