/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 23:03:29 GMT 2026
 */

package org.apache.bookkeeper.zookeeper;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bookkeeper.zookeeper.SimpleRetryPolicy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleRetryPolicy_ESTest extends SimpleRetryPolicy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom((-1419));
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-449L), (-1419));
      long long0 = simpleRetryPolicy0.nextRetryWaitTime((-2907), (-2221L));
      assertEquals((-4939L), long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-1L), (-5970));
      boolean boolean0 = simpleRetryPolicy0.allowRetry((-5970), (-5970));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy(0L, 0);
      long long0 = simpleRetryPolicy0.nextRetryWaitTime(0, 0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy(1L, (-702));
      long long0 = simpleRetryPolicy0.nextRetryWaitTime((-702), (-702));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-1857L), 1);
      boolean boolean0 = simpleRetryPolicy0.allowRetry((-457), (-1857L));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-449L), (-1419));
      boolean boolean0 = simpleRetryPolicy0.allowRetry(627, 0L);
      assertFalse(boolean0);
  }
}
