/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 23:03:29 GMT 2026
 */

package org.apache.bookkeeper.zookeeper;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bookkeeper.zookeeper.SimpleRetryPolicy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleRetryPolicy_ESTest extends SimpleRetryPolicy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom((-1419));
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-449L), (-1419));
      long long0 = simpleRetryPolicy0.nextRetryWaitTime((-2907), (-2221L));
      assertEquals((-4939L), long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-1L), (-5970));
      boolean boolean0 = simpleRetryPolicy0.allowRetry((-5970), (-5970));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy(0L, 0);
      long long0 = simpleRetryPolicy0.nextRetryWaitTime(0, 0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy(1L, (-702));
      long long0 = simpleRetryPolicy0.nextRetryWaitTime((-702), (-702));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-1857L), 1);
      boolean boolean0 = simpleRetryPolicy0.allowRetry((-457), (-1857L));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleRetryPolicy simpleRetryPolicy0 = new SimpleRetryPolicy((-449L), (-1419));
      boolean boolean0 = simpleRetryPolicy0.allowRetry(627, 0L);
      assertFalse(boolean0);
  }
}
