/* *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/* * This file was automatically generated by EvoSuite
 * Wed Jan 07 23:04:47 GMT 2026
 */

package org.apache.bookkeeper.bookie;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bookkeeper.bookie.SimpleEntryMemTable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleEntryMemTable_ESTest extends SimpleEntryMemTable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleEntryMemTable simpleEntryMemTable0 = new SimpleEntryMemTable((-1L));
      boolean boolean0 = simpleEntryMemTable0.isEmpty();
      assertEquals(0L, simpleEntryMemTable0.getEstimatedSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleEntryMemTable simpleEntryMemTable0 = new SimpleEntryMemTable((-1L));
      simpleEntryMemTable0.snapshot();
      assertEquals(0L, simpleEntryMemTable0.getEstimatedSize());
  }
}
