/*
 * This file was automatically generated by EvoSuite
 * Wed Jan 07 23:04:47 GMT 2026
 */

package org.apache.bookkeeper.bookie;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bookkeeper.bookie.SimpleEntryMemTable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleEntryMemTable_ESTest extends SimpleEntryMemTable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleEntryMemTable simpleEntryMemTable0 = new SimpleEntryMemTable((-1L));
      boolean boolean0 = simpleEntryMemTable0.isEmpty();
      assertEquals(0L, simpleEntryMemTable0.getEstimatedSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleEntryMemTable simpleEntryMemTable0 = new SimpleEntryMemTable((-1L));
      simpleEntryMemTable0.snapshot();
      assertEquals(0L, simpleEntryMemTable0.getEstimatedSize());
  }
}
