// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/JmsHeader.proto

package org.apache.hedwig.jms.message.header;

public final class JmsHeader {
  private JmsHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ProtocolVersion
      implements com.google.protobuf.ProtocolMessageEnum {
    VERSION_ONE(0, 1),
    ;
    
    public static final int VERSION_ONE_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static ProtocolVersion valueOf(int value) {
      switch (value) {
        case 1: return VERSION_ONE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProtocolVersion>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolVersion>() {
            public ProtocolVersion findValueByNumber(int number) {
              return ProtocolVersion.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.apache.hedwig.jms.message.header.JmsHeader.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ProtocolVersion[] VALUES = {
      VERSION_ONE, 
    };
    
    public static ProtocolVersion valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ProtocolVersion(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:Hedwig.Jms.Header.ProtocolVersion)
  }
  
  public interface JmsValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .Hedwig.Jms.Header.JmsValue.ValueType type = 1;
    boolean hasType();
    org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType getType();
    
    // optional bool booleanValue = 2;
    boolean hasBooleanValue();
    boolean getBooleanValue();
    
    // optional sint32 byteValue = 3;
    boolean hasByteValue();
    int getByteValue();
    
    // optional sint32 shortValue = 4;
    boolean hasShortValue();
    int getShortValue();
    
    // optional sint32 intValue = 5;
    boolean hasIntValue();
    int getIntValue();
    
    // optional sint64 longValue = 6;
    boolean hasLongValue();
    long getLongValue();
    
    // optional float floatValue = 7;
    boolean hasFloatValue();
    float getFloatValue();
    
    // optional double doubleValue = 8;
    boolean hasDoubleValue();
    double getDoubleValue();
    
    // optional string stringValue = 9;
    boolean hasStringValue();
    String getStringValue();
    
    // optional bytes bytesValue = 10;
    boolean hasBytesValue();
    com.google.protobuf.ByteString getBytesValue();
  }
  public static final class JmsValue extends
      com.google.protobuf.GeneratedMessage
      implements JmsValueOrBuilder {
    // Use JmsValue.newBuilder() to construct.
    private JmsValue(Builder builder) {
      super(builder);
    }
    private JmsValue(boolean noInit) {}
    
    private static final JmsValue defaultInstance;
    public static JmsValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public JmsValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hedwig.jms.message.header.JmsHeader.internal_static_Hedwig_Jms_Header_JmsValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hedwig.jms.message.header.JmsHeader.internal_static_Hedwig_Jms_Header_JmsValue_fieldAccessorTable;
    }
    
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      BOOLEAN(0, 1),
      BYTE(1, 2),
      SHORT(2, 3),
      INT(3, 4),
      LONG(4, 5),
      FLOAT(5, 6),
      DOUBLE(6, 7),
      STRING(7, 8),
      BYTES(8, 9),
      ;
      
      public static final int BOOLEAN_VALUE = 1;
      public static final int BYTE_VALUE = 2;
      public static final int SHORT_VALUE = 3;
      public static final int INT_VALUE = 4;
      public static final int LONG_VALUE = 5;
      public static final int FLOAT_VALUE = 6;
      public static final int DOUBLE_VALUE = 7;
      public static final int STRING_VALUE = 8;
      public static final int BYTES_VALUE = 9;
      
      
      public final int getNumber() { return value; }
      
      public static ValueType valueOf(int value) {
        switch (value) {
          case 1: return BOOLEAN;
          case 2: return BYTE;
          case 3: return SHORT;
          case 4: return INT;
          case 5: return LONG;
          case 6: return FLOAT;
          case 7: return DOUBLE;
          case 8: return STRING;
          case 9: return BYTES;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ValueType[] VALUES = {
        BOOLEAN, BYTE, SHORT, INT, LONG, FLOAT, DOUBLE, STRING, BYTES, 
      };
      
      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ValueType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Hedwig.Jms.Header.JmsValue.ValueType)
    }
    
    private int bitField0_;
    // required .Hedwig.Jms.Header.JmsValue.ValueType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType getType() {
      return type_;
    }
    
    // optional bool booleanValue = 2;
    public static final int BOOLEANVALUE_FIELD_NUMBER = 2;
    private boolean booleanValue_;
    public boolean hasBooleanValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getBooleanValue() {
      return booleanValue_;
    }
    
    // optional sint32 byteValue = 3;
    public static final int BYTEVALUE_FIELD_NUMBER = 3;
    private int byteValue_;
    public boolean hasByteValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getByteValue() {
      return byteValue_;
    }
    
    // optional sint32 shortValue = 4;
    public static final int SHORTVALUE_FIELD_NUMBER = 4;
    private int shortValue_;
    public boolean hasShortValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getShortValue() {
      return shortValue_;
    }
    
    // optional sint32 intValue = 5;
    public static final int INTVALUE_FIELD_NUMBER = 5;
    private int intValue_;
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getIntValue() {
      return intValue_;
    }
    
    // optional sint64 longValue = 6;
    public static final int LONGVALUE_FIELD_NUMBER = 6;
    private long longValue_;
    public boolean hasLongValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getLongValue() {
      return longValue_;
    }
    
    // optional float floatValue = 7;
    public static final int FLOATVALUE_FIELD_NUMBER = 7;
    private float floatValue_;
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public float getFloatValue() {
      return floatValue_;
    }
    
    // optional double doubleValue = 8;
    public static final int DOUBLEVALUE_FIELD_NUMBER = 8;
    private double doubleValue_;
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public double getDoubleValue() {
      return doubleValue_;
    }
    
    // optional string stringValue = 9;
    public static final int STRINGVALUE_FIELD_NUMBER = 9;
    private java.lang.Object stringValue_;
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          stringValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes bytesValue = 10;
    public static final int BYTESVALUE_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString bytesValue_;
    public boolean hasBytesValue() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public com.google.protobuf.ByteString getBytesValue() {
      return bytesValue_;
    }
    
    private void initFields() {
      type_ = org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType.BOOLEAN;
      booleanValue_ = false;
      byteValue_ = 0;
      shortValue_ = 0;
      intValue_ = 0;
      longValue_ = 0L;
      floatValue_ = 0F;
      doubleValue_ = 0D;
      stringValue_ = "";
      bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, booleanValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, byteValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, shortValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt32(5, intValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeSInt64(6, longValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, floatValue_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, doubleValue_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, bytesValue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, booleanValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, byteValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, shortValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, intValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, longValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, floatValue_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, doubleValue_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, bytesValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hedwig.jms.message.header.JmsHeader.JmsValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hedwig.jms.message.header.JmsHeader.JmsValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hedwig.jms.message.header.JmsHeader.JmsValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hedwig.jms.message.header.JmsHeader.internal_static_Hedwig_Jms_Header_JmsValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hedwig.jms.message.header.JmsHeader.internal_static_Hedwig_Jms_Header_JmsValue_fieldAccessorTable;
      }
      
      // Construct using org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType.BOOLEAN;
        bitField0_ = (bitField0_ & ~0x00000001);
        booleanValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        byteValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        shortValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        intValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        longValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        floatValue_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        bytesValue_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.getDescriptor();
      }
      
      public org.apache.hedwig.jms.message.header.JmsHeader.JmsValue getDefaultInstanceForType() {
        return org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.getDefaultInstance();
      }
      
      public org.apache.hedwig.jms.message.header.JmsHeader.JmsValue build() {
        org.apache.hedwig.jms.message.header.JmsHeader.JmsValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hedwig.jms.message.header.JmsHeader.JmsValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hedwig.jms.message.header.JmsHeader.JmsValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hedwig.jms.message.header.JmsHeader.JmsValue buildPartial() {
        org.apache.hedwig.jms.message.header.JmsHeader.JmsValue result = new org.apache.hedwig.jms.message.header.JmsHeader.JmsValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.booleanValue_ = booleanValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.byteValue_ = byteValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.shortValue_ = shortValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.intValue_ = intValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.longValue_ = longValue_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.floatValue_ = floatValue_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.doubleValue_ = doubleValue_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.bytesValue_ = bytesValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hedwig.jms.message.header.JmsHeader.JmsValue) {
          return mergeFrom((org.apache.hedwig.jms.message.header.JmsHeader.JmsValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hedwig.jms.message.header.JmsHeader.JmsValue other) {
        if (other == org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasBooleanValue()) {
          setBooleanValue(other.getBooleanValue());
        }
        if (other.hasByteValue()) {
          setByteValue(other.getByteValue());
        }
        if (other.hasShortValue()) {
          setShortValue(other.getShortValue());
        }
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasLongValue()) {
          setLongValue(other.getLongValue());
        }
        if (other.hasFloatValue()) {
          setFloatValue(other.getFloatValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasStringValue()) {
          setStringValue(other.getStringValue());
        }
        if (other.hasBytesValue()) {
          setBytesValue(other.getBytesValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType value = org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              booleanValue_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              byteValue_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              shortValue_ = input.readSInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              intValue_ = input.readSInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              longValue_ = input.readSInt64();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              floatValue_ = input.readFloat();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              doubleValue_ = input.readDouble();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              stringValue_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              bytesValue_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .Hedwig.Jms.Header.JmsValue.ValueType type = 1;
      private org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType type_ = org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType.BOOLEAN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType getType() {
        return type_;
      }
      public Builder setType(org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.ValueType.BOOLEAN;
        onChanged();
        return this;
      }
      
      // optional bool booleanValue = 2;
      private boolean booleanValue_ ;
      public boolean hasBooleanValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getBooleanValue() {
        return booleanValue_;
      }
      public Builder setBooleanValue(boolean value) {
        bitField0_ |= 0x00000002;
        booleanValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearBooleanValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        booleanValue_ = false;
        onChanged();
        return this;
      }
      
      // optional sint32 byteValue = 3;
      private int byteValue_ ;
      public boolean hasByteValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getByteValue() {
        return byteValue_;
      }
      public Builder setByteValue(int value) {
        bitField0_ |= 0x00000004;
        byteValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearByteValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        byteValue_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 shortValue = 4;
      private int shortValue_ ;
      public boolean hasShortValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getShortValue() {
        return shortValue_;
      }
      public Builder setShortValue(int value) {
        bitField0_ |= 0x00000008;
        shortValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearShortValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        shortValue_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 intValue = 5;
      private int intValue_ ;
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getIntValue() {
        return intValue_;
      }
      public Builder setIntValue(int value) {
        bitField0_ |= 0x00000010;
        intValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        intValue_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint64 longValue = 6;
      private long longValue_ ;
      public boolean hasLongValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getLongValue() {
        return longValue_;
      }
      public Builder setLongValue(long value) {
        bitField0_ |= 0x00000020;
        longValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        longValue_ = 0L;
        onChanged();
        return this;
      }
      
      // optional float floatValue = 7;
      private float floatValue_ ;
      public boolean hasFloatValue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getFloatValue() {
        return floatValue_;
      }
      public Builder setFloatValue(float value) {
        bitField0_ |= 0x00000040;
        floatValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        floatValue_ = 0F;
        onChanged();
        return this;
      }
      
      // optional double doubleValue = 8;
      private double doubleValue_ ;
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public double getDoubleValue() {
        return doubleValue_;
      }
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000080;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000080);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }
      
      // optional string stringValue = 9;
      private java.lang.Object stringValue_ = "";
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStringValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        stringValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000100);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      void setStringValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        stringValue_ = value;
        onChanged();
      }
      
      // optional bytes bytesValue = 10;
      private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBytesValue() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public com.google.protobuf.ByteString getBytesValue() {
        return bytesValue_;
      }
      public Builder setBytesValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        bytesValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearBytesValue() {
        bitField0_ = (bitField0_ & ~0x00000200);
        bytesValue_ = getDefaultInstance().getBytesValue();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Hedwig.Jms.Header.JmsValue)
    }
    
    static {
      defaultInstance = new JmsValue(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Hedwig.Jms.Header.JmsValue)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Hedwig_Jms_Header_JmsValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Hedwig_Jms_Header_JmsValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/protobuf/JmsHeader.proto\022\021Hed" +
      "wig.Jms.Header\"\343\002\n\010JmsValue\0223\n\004type\030\001 \002(" +
      "\0162%.Hedwig.Jms.Header.JmsValue.ValueType" +
      "\022\024\n\014booleanValue\030\002 \001(\010\022\021\n\tbyteValue\030\003 \001(" +
      "\021\022\022\n\nshortValue\030\004 \001(\021\022\020\n\010intValue\030\005 \001(\021\022" +
      "\021\n\tlongValue\030\006 \001(\022\022\022\n\nfloatValue\030\007 \001(\002\022\023" +
      "\n\013doubleValue\030\010 \001(\001\022\023\n\013stringValue\030\t \001(\t" +
      "\022\022\n\nbytesValue\030\n \001(\014\"n\n\tValueType\022\013\n\007BOO" +
      "LEAN\020\001\022\010\n\004BYTE\020\002\022\t\n\005SHORT\020\003\022\007\n\003INT\020\004\022\010\n\004" +
      "LONG\020\005\022\t\n\005FLOAT\020\006\022\n\n\006DOUBLE\020\007\022\n\n\006STRING\020",
      "\010\022\t\n\005BYTES\020\t*\"\n\017ProtocolVersion\022\017\n\013VERSI" +
      "ON_ONE\020\001B(\n$org.apache.hedwig.jms.messag" +
      "e.headerH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Hedwig_Jms_Header_JmsValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Hedwig_Jms_Header_JmsValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Hedwig_Jms_Header_JmsValue_descriptor,
              new java.lang.String[] { "Type", "BooleanValue", "ByteValue", "ShortValue", "IntValue", "LongValue", "FloatValue", "DoubleValue", "StringValue", "BytesValue", },
              org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.class,
              org.apache.hedwig.jms.message.header.JmsHeader.JmsValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
