/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 09 21:14:01 GMT 2026
 */

package org.apache.bookkeeper.zookeeper;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bookkeeper.zookeeper.ExponentialBackoffRetryPolicy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ExponentialBackoffRetryPolicy_ESTest extends ExponentialBackoffRetryPolicy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy0 = new ExponentialBackoffRetryPolicy(1L, 1208);
      Random.setNextRandom(1208);
      long long0 = exponentialBackoffRetryPolicy0.nextRetryWaitTime(1208, (-1626L));
      assertEquals(1208L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy0 = new ExponentialBackoffRetryPolicy(0L, 0);
      boolean boolean0 = exponentialBackoffRetryPolicy0.allowRetry(0, 106);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy0 = new ExponentialBackoffRetryPolicy(0L, 0);
      long long0 = exponentialBackoffRetryPolicy0.nextRetryWaitTime(106, 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy0 = new ExponentialBackoffRetryPolicy((-1L), 2140);
      long long0 = exponentialBackoffRetryPolicy0.nextRetryWaitTime(2140, 2140);
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy0 = new ExponentialBackoffRetryPolicy((-1L), 2140);
      boolean boolean0 = exponentialBackoffRetryPolicy0.allowRetry(0, (-1L));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy0 = new ExponentialBackoffRetryPolicy(1825L, (-2690));
      boolean boolean0 = exponentialBackoffRetryPolicy0.allowRetry(374, 1704L);
      assertFalse(boolean0);
  }
}
