# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x18\x62ookkeeper.proto.cluster\"*\n\x14ServerAssignmentData\x12\x12\n\ncontainers\x18\x01 \x03(\x03\"\xc6\x01\n\x15\x43lusterAssignmentData\x12M\n\x07servers\x18\x01 \x03(\x0b\x32<.bookkeeper.proto.cluster.ClusterAssignmentData.ServersEntry\x1a^\n\x0cServersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12=\n\x05value\x18\x02 \x01(\x0b\x32..bookkeeper.proto.cluster.ServerAssignmentData:\x02\x38\x01\"1\n\x0f\x43lusterMetadata\x12\x1e\n\x16num_storage_containers\x18\x01 \x01(\x03\x42.\n*org.apache.bookkeeper.stream.proto.clusterP\x01\x62\x06proto3')



_SERVERASSIGNMENTDATA = DESCRIPTOR.message_types_by_name['ServerAssignmentData']
_CLUSTERASSIGNMENTDATA = DESCRIPTOR.message_types_by_name['ClusterAssignmentData']
_CLUSTERASSIGNMENTDATA_SERVERSENTRY = _CLUSTERASSIGNMENTDATA.nested_types_by_name['ServersEntry']
_CLUSTERMETADATA = DESCRIPTOR.message_types_by_name['ClusterMetadata']
ServerAssignmentData = _reflection.GeneratedProtocolMessageType('ServerAssignmentData', (_message.Message,), {
  'DESCRIPTOR' : _SERVERASSIGNMENTDATA,
  '__module__' : 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.cluster.ServerAssignmentData)
  })
_sym_db.RegisterMessage(ServerAssignmentData)

ClusterAssignmentData = _reflection.GeneratedProtocolMessageType('ClusterAssignmentData', (_message.Message,), {

  'ServersEntry' : _reflection.GeneratedProtocolMessageType('ServersEntry', (_message.Message,), {
    'DESCRIPTOR' : _CLUSTERASSIGNMENTDATA_SERVERSENTRY,
    '__module__' : 'cluster_pb2'
    # @@protoc_insertion_point(class_scope:bookkeeper.proto.cluster.ClusterAssignmentData.ServersEntry)
    })
  ,
  'DESCRIPTOR' : _CLUSTERASSIGNMENTDATA,
  '__module__' : 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.cluster.ClusterAssignmentData)
  })
_sym_db.RegisterMessage(ClusterAssignmentData)
_sym_db.RegisterMessage(ClusterAssignmentData.ServersEntry)

ClusterMetadata = _reflection.GeneratedProtocolMessageType('ClusterMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERMETADATA,
  '__module__' : 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.cluster.ClusterMetadata)
  })
_sym_db.RegisterMessage(ClusterMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*org.apache.bookkeeper.stream.proto.clusterP\001'
  _CLUSTERASSIGNMENTDATA_SERVERSENTRY._options = None
  _CLUSTERASSIGNMENTDATA_SERVERSENTRY._serialized_options = b'8\001'
  _SERVERASSIGNMENTDATA._serialized_start=43
  _SERVERASSIGNMENTDATA._serialized_end=85
  _CLUSTERASSIGNMENTDATA._serialized_start=88
  _CLUSTERASSIGNMENTDATA._serialized_end=286
  _CLUSTERASSIGNMENTDATA_SERVERSENTRY._serialized_start=192
  _CLUSTERASSIGNMENTDATA_SERVERSENTRY._serialized_end=286
  _CLUSTERMETADATA._serialized_start=288
  _CLUSTERMETADATA._serialized_end=337
# @@protoc_insertion_point(module_scope)
