# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv_store.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bookkeeper.proto.kv_rpc_pb2 as kv__rpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_store.proto\x12\x19\x62ookkeeper.proto.kv.store\x1a\x0ckv_rpc.proto\"\x97\x01\n\x07KeyMeta\x12\x17\n\x0f\x63reate_revision\x18\x01 \x01(\x03\x12\x14\n\x0cmod_revision\x18\x02 \x01(\x03\x12\x0f\n\x07version\x18\x03 \x01(\x03\x12\x38\n\nvalue_type\x18\x04 \x01(\x0e\x32$.bookkeeper.proto.kv.store.ValueType\x12\x12\n\nexpireTime\x18\x05 \x01(\x03\"\x0c\n\nNopRequest\"\xbc\x02\n\x07\x43ommand\x12\x38\n\x07nop_req\x18\x01 \x01(\x0b\x32%.bookkeeper.proto.kv.store.NopRequestH\x00\x12\x36\n\x07put_req\x18\x02 \x01(\x0b\x32#.bookkeeper.proto.kv.rpc.PutRequestH\x00\x12\x41\n\ndelete_req\x18\x03 \x01(\x0b\x32+.bookkeeper.proto.kv.rpc.DeleteRangeRequestH\x00\x12\x36\n\x07txn_req\x18\x04 \x01(\x0b\x32#.bookkeeper.proto.kv.rpc.TxnRequestH\x00\x12=\n\x08incr_req\x18\x05 \x01(\x0b\x32).bookkeeper.proto.kv.rpc.IncrementRequestH\x00\x42\x05\n\x03req\"*\n\x08\x46ileInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\t\"}\n\x12\x43heckpointMetadata\x12\r\n\x05\x66iles\x18\x01 \x03(\t\x12\x0c\n\x04txid\x18\x02 \x01(\x0c\x12\x12\n\ncreated_at\x18\x03 \x01(\x04\x12\x36\n\tfileInfos\x18\x04 \x03(\x0b\x32#.bookkeeper.proto.kv.store.FileInfo*\"\n\tValueType\x12\t\n\x05\x42YTES\x10\x00\x12\n\n\x06NUMBER\x10\x01\x42/\n+org.apache.bookkeeper.stream.proto.kv.storeP\x01\x62\x06proto3')

_VALUETYPE = DESCRIPTOR.enum_types_by_name['ValueType']
ValueType = enum_type_wrapper.EnumTypeWrapper(_VALUETYPE)
BYTES = 0
NUMBER = 1


_KEYMETA = DESCRIPTOR.message_types_by_name['KeyMeta']
_NOPREQUEST = DESCRIPTOR.message_types_by_name['NopRequest']
_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_FILEINFO = DESCRIPTOR.message_types_by_name['FileInfo']
_CHECKPOINTMETADATA = DESCRIPTOR.message_types_by_name['CheckpointMetadata']
KeyMeta = _reflection.GeneratedProtocolMessageType('KeyMeta', (_message.Message,), {
  'DESCRIPTOR' : _KEYMETA,
  '__module__' : 'kv_store_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.kv.store.KeyMeta)
  })
_sym_db.RegisterMessage(KeyMeta)

NopRequest = _reflection.GeneratedProtocolMessageType('NopRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOPREQUEST,
  '__module__' : 'kv_store_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.kv.store.NopRequest)
  })
_sym_db.RegisterMessage(NopRequest)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'kv_store_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.kv.store.Command)
  })
_sym_db.RegisterMessage(Command)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), {
  'DESCRIPTOR' : _FILEINFO,
  '__module__' : 'kv_store_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.kv.store.FileInfo)
  })
_sym_db.RegisterMessage(FileInfo)

CheckpointMetadata = _reflection.GeneratedProtocolMessageType('CheckpointMetadata', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPOINTMETADATA,
  '__module__' : 'kv_store_pb2'
  # @@protoc_insertion_point(class_scope:bookkeeper.proto.kv.store.CheckpointMetadata)
  })
_sym_db.RegisterMessage(CheckpointMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+org.apache.bookkeeper.stream.proto.kv.storeP\001'
  _VALUETYPE._serialized_start=717
  _VALUETYPE._serialized_end=751
  _KEYMETA._serialized_start=60
  _KEYMETA._serialized_end=211
  _NOPREQUEST._serialized_start=213
  _NOPREQUEST._serialized_end=225
  _COMMAND._serialized_start=228
  _COMMAND._serialized_end=544
  _FILEINFO._serialized_start=546
  _FILEINFO._serialized_end=588
  _CHECKPOINTMETADATA._serialized_start=590
  _CHECKPOINTMETADATA._serialized_end=715
# @@protoc_insertion_point(module_scope)
