name: BookKeeper
run-name: ${{ github.actor }} Tests
on:
  pull_request:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile the image
        run: mvn clean compile
      - name: Unit Tests
        run: mvn clean test
      - name: Integration Tests
        run: mvn clean verify
  
